### ISSUE TITLE
Copy From Previous, Duplicates Specimen Parts

### ISSUE THREAD

**Issue by zwickerr** [BernhardWebstudio/DataShot_DesktopApp#18]
When "Copy prev" was used, entries in the "Specimen Parts" list appear twice after DataShot has been restarted.

Edit: I just noticed that it is not necessary to restart DataShot for the second entry to appear in the list. It is enough to repeat the search.

**Comment by GenieTim** [comment]
Should be fixed in 1.10 (release in ca. 1 hour). A database upgrade will be necessary, as apparently the a few data entity relationship directions were mixed up since always. In my tests, I did not have any issues afterwards using elder versions of DataShot with the new database, but maybe you will want to check first with the test database (ask @ETHEntColl for the credentials).

**Comment by zwickerr** [comment]
How will the database upgrade work? When will the upgrade happen? The others are currently still working with 1.8.

**Comment by GenieTim** [comment]
Ideally, if everything goes as glad as it did with my local test database, you will be asked by the program and just have to press "OK".

I know that the others are still working with 1.8, that's why I recommend to test the upgrade on the test database and, if that succeeded, afterwards test 1.8 on the upgraded test database. This way, you can make sure the others will not have any problems after you upgraded to 1.10 in the production database too.

**Comment by zwickerr** [comment]
Ok, then I need to find a way to get the credentials for the test database. I don't see a way to message @ETHEntColl, but I will ask @greeffm.

**Comment by ETHEntColl** [comment]
I have the credentials for the test database; I can help with this on Monday morning. Best, melissa
