### ISSUE TITLE
Errors when pasting

### ISSUE THREAD

**Issue by Commodore95** [BernhardWebstudio/DataShot_DesktopApp#28]
-Bei Reinkopieren, falls etwas schon enthalten ist, gibts eine Fehlermeldung
-Bei Reinkopieren, numbers and more type, das drop down menu ist (meistens) nicht verfügbar

Falls du mehr Informationen benötigst, lass es mich wissen.

**Comment by GenieTim** [comment]
I am having slight troubles replicating the issue. Would you mind, do you

 - Copy or copy & save one entity, then switch to another one, click paste even though it will overwrite some fields, then you get an error? Is this correct? What is the error you get? Any specific entries I could replicate the issue with?
 - I can replicate this one. Should be fixed in the newest pre-release.

Thanks & best regards
