### ISSUE TITLE
UTF-8 in verbatim locality

### ISSUE THREAD

**Issue by greeffm** [BernhardWebstudio/DataShot_DesktopApp#6]
Currently, you can type all kinds of letters into the verbatim field (e.g. cyrillic letters). The letters will appear correctly while your filling in the data. However, once the data are saved, the letters are replaced with incorrect characters (e.g. &%/...). It seems that this field doesn't comply with UTF-8 standards. 

To do: The field "verbatim locality" should be modified that it correctly stores and displays all kinds of letters.

**Comment by GenieTim** [comment]
I am unfortunately not able to fully replicate the issue. I see that "ETHZ-ENT0009399" has a value of "O?p. ??????????" in the database. But when editing the specimen to have a Verbatim Locality of (in my replication) "Oⱡķǥềp.  →θηⓇϕ⊗ɑ⁰ʟ", the value gets saved as-is and the value survives restarting database & DataShot. Is it possible that the question marks were entered as such, question marks?

I can see that indeed some characters are not possible to be entered (emojis, to be specific), but this is because of the database setup which would have to be adapted. In any case, this would lead to issues with saving the specimen and would not lead to question marks.

**Comment by zwickerr** [comment]
I tested it again on ETHZ-ENT0026293. After entering "Окр. Минусннска" as verbatim locality it is shown correctly in the field, as well as in the list of search results.
After the search is repeated however, in the search results and in the verbatim locality field "???. ??????????" is shown.

**Comment by GenieTim** [comment]
I am unfortunately still not able to replicate the issue. I fear it could be related to the outdated MariaDB version (you have 5.5., current is 10.4), but I am not sure. In any case, I will keep looking but currently do not have the rights to upgrade your MariaDB instance. I would also warn you not to do that before every DataShot instance is on at least DataShot 1.9, as the elder DataShot versions were not compatible with the newest MySQL version.

**Comment by GenieTim** [comment]
I think we have found the last cases where this error occurred, right? I will close this issue now.
